### ISSUE TITLE
Overview of Issues & PR

### ISSUE THREAD

**Issue by 1000miles** [rubyberlin/code-of-conduct#89]
To get a better overview of current open and cross-referenced tickets and pull requests, here is an overview list for our next in-person-meeting in march. :)

# 1. Versioning

- [ ] 1. [Versioning](https://github.com/rubyberlin/code-of-conduct/issues/7) – Jun 3, 2014 (open)
- [ ] 1.1 [Change process](https://github.com/rubyberlin/code-of-conduct/issues/39) – Febr 6, 2015 (open)
- [ ] 1.1.1 [Display of Violence](https://github.com/rubyberlin/code-of-conduct/issues/40) – Febr 6, 2015 (open)
- [x] 1.1.1.1 [Statement addressing the display of inappropriate content](https://github.com/rubyberlin/code-of-conduct/pull/54) (PR) – Mar 25, 2015 (unmerged, closed)

# 2. Content (Behavior)

- [ ] 2. ["Attempt collaboration before conflict."](https://github.com/rubyberlin/code-of-conduct/issues/8) – Jun 3, 2014 (open)
- [x] 2.1 [Added a first draft for the spanish translation of the CoC.](https://github.com/rubyberlin/code-of-conduct/pull/23) – Jun 3, 2014 (closed)
- [x] 2.1.1 [Changed writing of some phrases to be more gender inclusive.](https://github.com/DjangoMeetupBA/code-of-conduct/pull/2) – Aug 8, 2014 (merged)
- [ ] 2.1.2 [Expected behavior](https://github.com/rubyberlin/code-of-conduct/issues/58) – May 19, 2015 (open)
- [ ] 2.1.2.1 [In-Person meeting for future changes](https://github.com/rubyberlin/code-of-conduct/issues/86) – Febr 18, 2016 (open)

# 3. Content (Jokes)

- [ ] 3. [“Jokes” Against Other Programming Languages](https://github.com/rubyberlin/code-of-conduct/issues/19) – Jul 21, 2014 (open)

# 4. Licence

- [ ] 4. [A note regarding a license for the BCoC?](https://github.com/rubyberlin/code-of-conduct/issues/30) – Sept 8, 2014 (open)
- [x] 4.1 [Added license section to CoC](https://github.com/rubyberlin/code-of-conduct/pull/31) – (PR) Sept 8, 2014 (closed)

# 5. Orga (Change process)

- [ ] 5. [Change process](https://github.com/rubyberlin/code-of-conduct/issues/39) – Febr 6, 2015 (open) – DUPLICATE
- [ ] 5.1 [Display of Violence](https://github.com/rubyberlin/code-of-conduct/issues/40) – Febr 6, 2015 (open) – DUPLICATE 2
- [ ] 5.2 [Include statement addressing violent imagery](https://github.com/rubyberlin/code-of-conduct/pull/45) (PR) Mar 2, 2015 (open)
- [ ] 5.2.1 [Display of Violence](https://github.com/rubyberlin/code-of-conduct/issues/40) – Febr 6, 2015 (open) – DUPLICATE 3
- [x] 5.2.2 [Statement addressing the display of inappropriate content]( https://github.com/rubyberlin/code-of-conduct/pull/54) – (PR) Mar 25, 2015 (unmerged, closed)
- [ ] 5.2.2.1 [Display of Violence](https://github.com/rubyberlin/code-of-conduct/issues/40) – Febr 6, 2015 (open) – DUPLICATE 4
- [ ] 5.2.2.2 [Include statement addressing violent imagery](https://github.com/rubyberlin/code-of-conduct/pull/45) (PR) Mar 2, 2015 (open) – DUPLICATE 2
- [x] 5.3 [Adjust language to be more gender neutral](https://github.com/rubyberlin/code-of-conduct/pull/59) (PR) Jun 5, 2015 (merged)

# 6. Content (Violence Display)

- [ ] 6. [Display of Violence](https://github.com/rubyberlin/code-of-conduct/issues/40) – Febr 6, 2015 (open) – DUPLICATE 5
- [ ] 6.1 [Include statement addressing violent imagery](https://github.com/rubyberlin/code-of-conduct/pull/45) – (PR) Mar 2, 2015 – DUPLICATE 2
- [x] 6.2 [Statement addressing the display of inappropriate content](https://github.com/rubyberlin/code-of-conduct/pull/54) – (PR) Mar 25, 2015 (unmerged, closed) – DUPLICATE 2

# 7. Content (Schools & Organizations)

- [ ] 7. [Add organisations or schools as a separate group](https://github.com/rubyberlin/code-of-conduct/issues/43) Febr 27, 2015 (open)
- [ ] 7.1 [Display of Violence](https://github.com/rubyberlin/code-of-conduct/issues/40) – Febr 6, 2015 (open) – DUPLICATE 6

# 8. Content (Gender)

- [ ] 8. [Gendering in der deutschen Version](https://github.com/rubyberlin/code-of-conduct/issues/44) – Febr 28, 2015 (open)
- [ ] 8.1 [Adjust language to be more gender neutral](https://github.com/rubyberlin/code-of-conduct/pull/59) – Jun 5, 2015 (PR) - DUPLICATE 2
- [ ] 8.2 [In-Person meeting for future changes](https://github.com/rubyberlin/code-of-conduct/issues/86) – Febr 18, 2016  (open) - DUPLICATE 3

# 9. Licence

- [ ] 9. [What is the license for this work?](https://github.com/rubyberlin/code-of-conduct/issues/57) – Apr 28, 2015 (open)

# 10. Content (Expected Behavior)

- [ ] 10. [Expected Behavior](https://github.com/rubyberlin/code-of-conduct/issues/58) – May 19, 2015 (open)
- [ ] 10.1 [In-Person meeting for future changes](https://github.com/rubyberlin/code-of-conduct/issues/86) – Febr 18, 2016  (open) - DUPLICATE 4

# 11. Content (Origin & Ability)

- [ ] 11. ["Herkunft" und "Befähigung"](https://github.com/rubyberlin/code-of-conduct/issues/61) – May 21, 2015 (open)
- [ ] 11.1 [Adjust language to be more gender neutral](https://github.com/rubyberlin/code-of-conduct/pull/59) – Jun 5, 2015 (PR) - DUPLICATE 3
- [ ] 11.2 [Get professional expertise by foundations](https://github.com/rubyberlin/code-of-conduct/issues/62) – May 23, 2015 (open)
- [ ] 11.2.1 [Improvements to comprehensibility and extension of categories](https://github.com/rubyberlin/code-of-conduct/pull/63) – May 23, 2015 (open)
- [ ] 11.2.1.1 [Include statement addressing violent imagery](https://github.com/rubyberlin/code-of-conduct/pull/45) – (PR) Mar 2, 2015 (open) – DUPLICATE 3
- [ ] 11.2.1.2 [Add gender identity and expression](https://github.com/rubyberlin/code-of-conduct/pull/76) – (PR) Nov 2, 2015 (open)
- [ ] 11.2.1.2.1 [In-Person meeting for future changes](https://github.com/rubyberlin/code-of-conduct/issues/86) – (PR) Febr 18, 2016 (open) - DUPLICATE 5

# 12. Content & Collaboration (Get Expertise)

- [ ] 12.2 [Get professional expertise by foundations](https://github.com/rubyberlin/code-of-conduct/issues/62) – May 23, 2015 (open) - DUPLICATE 2

# 13. Content (Authentic Behavior)

- [ ] 13. [Remove authentic behaviour?](https://github.com/rubyberlin/code-of-conduct/issues/81) – Jan 2, 2016 (open)
- [ ] 13.1 [In-Person meeting for future changes](https://github.com/rubyberlin/code-of-conduct/issues/86) – Febr 18, 2016 (open) - DUPLICATE 6

# 14. Content (CoC Short Version for Slides)

- [ ] 14. [Short summary for slides](https://github.com/rubyberlin/code-of-conduct/issues/84) – Febr 2016 (open)

# 15. Orga: In-Person-Meeting

- [ ] 15. [In-Person meeting for future changes](https://github.com/rubyberlin/code-of-conduct/issues/86) – Febr 18, 2016 (open) - DUPLICATE 6

14. PULL REQUESTS
============

- [ ] 14.1 [Include statement addressing violent imagery](https://github.com/rubyberlin/code-of-conduct/pull/45) (PR) Mar 2, 2015 (open) - DUPLICATE 4
- [ ] 14.2 [Improvements to comprehensibility and extension of categories](https://github.com/rubyberlin/code-of-conduct/pull/63) – May 23, 2015 (open) - DUPLICATE 2
- [ ] 14.3 [Add gender identity and expression](https://github.com/rubyberlin/code-of-conduct/pull/76) – (PR) Nov 2, 2015 (open) - DUPLICATE 2

**Comment by skade** [comment]
This is... thorough :). <3

Thanks for the effort!
